[profile.default]
src = "src"
out = "out"
libs = ["lib"]
exclude = ["script/deprecated/**"]

# Enable optimizations for deployment (required for large contracts)
via_ir = false
optimizer = true
optimizer_runs = 1000

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/"
]

# Forked testing configuration
[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
