name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Smart Contract Tests
  test-contracts:
    name: Test Smart Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
      
      - name: Run Forge tests
        run: |
          forge test -v
        id: test

  # Frontend Tests and Linting
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
        continue-on-error: true
      
      - name: Run tests
        run: npm test
        continue-on-error: true
      
      - name: Build frontend
        run: npm run build

  # Deploy to GitHub Pages (only on push to main/master)
  deploy-frontend:
    name: Deploy Frontend
    needs: [test-contracts, test-frontend]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/build
          branch: gh-pages
          clean: true

  # Optional: Deploy contracts to testnet (only on push to main/master)
  deploy-contracts:
    name: Deploy Contracts to Testnet
    needs: [test-contracts]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Deploy to Sepolia
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
        run: |
          # Skip if secrets are not set
          if [ -z "$PRIVATE_KEY" ] || [ -z "$RPC_URL" ]; then
            echo "Skipping deployment as secrets are not set"
            exit 0
          fi
          
          # Deploy contracts
          forge script script/DeploySepolia.s.sol:DeploySepolia --rpc-url $RPC_URL --broadcast --verify
        continue-on-error: true
